### ISSUE TITLE
Is it possible to add a function that can show the fox position?

### ISSUE THREAD

**Issue by EnderByEndera** [daemitus/FauxHollowsSolver#1]

**Comment by daemitus** [comment]
Last time I looked, no.

**Comment by gamescom15** [comment]
It's not completely random where the foxes spawn.

[This Sheet ](https://docs.google.com/spreadsheets/d/1mUyCzlzDmdXMwaSTUgWXtEA45oJNn-iB4_bVM43zf58/edit#gid=2064513493)  vaguely explains the positions that the fox can be in. 

Note that there's usually more than one positions the fox can be in

**Comment by chrisgreatest** [comment]
https://sturalke.github.io/FauxHollowsProbabilisticSolver/

There's also a little solver here that does it too, and you can check the box to show potential fox spawns based on your pattern. It would be super cool to have this toggle in this addon, perhaps just highlight potential spots in purple outline but otherwise keep the addon the same.

**Comment by DarkDestry** [comment]
Theres this historical record of fox locations
https://docs.google.com/spreadsheets/d/1mUyCzlzDmdXMwaSTUgWXtEA45oJNn-iB4_bVM43zf58/edit#gid=49331949

**Comment by daemitus** [comment]
We could add it, though im a bit leery about modifying this and being
unable to test while not subbed.

**Comment by DarkDestry** [comment]
Would volunteer to test if I hadnt already cleared it for the week.

You can push it as a beta and gather feedback I guess?

**Comment by Diorik** [comment]
> Theres this historical record of fox locations https://docs.google.com/spreadsheets/d/1mUyCzlzDmdXMwaSTUgWXtEA45oJNn-iB4_bVM43zf58/edit#gid=49331949

Reiterating this, this sheet has been extremely reliable.

**Comment by bidaumm** [comment]
Yeah, as long as you know the position of the sword and chest/coffer the positions that're shown on the sheet are the guaranteed locations the fox CAN spawn in (but not guaranteed that it'll be there on that attempt). Would be very useful to have, as right now the addon isn't 100% best potential action, especially for the 2nd attempt where getting the points for sword isn't always needed vs potential +135 for faux+coffer

**Comment by gamescom15** [comment]
This has since been implemented in [this plugin](https://github.com/awgil/vfaux).
